name: python-test
on: push
jobs:
  python_code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get_code
        uses: actions/checkout@v3
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run the code 
        run: python iris_classification.py

