name: python-test
on: [push,workflow_dispatch] # added multiple triggers , workflow_dispatch -- manual trigger
jobs:
  python_code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get_code
        uses: actions/checkout@v3
      - name: get python 3.8
        uses: actions/setup-python@v4
        with:
            python-version: '3.9' # this will set up python 3,.9 as default 
            cache: 'pip' # caching pip dependencies: 
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          python --version
      - name: run the code 
        run: python iris_classification.py
  build_docker:
    needs: python_code_test  # will run only after successful completion of python_code_test job
    runs-on:  ubuntu-latest  # every job has its own runner and there are isolated from each other
    steps:                   # jobs will run in parallel by default
      - name: Get_code
        uses: actions/checkout@v3
      - name: get python 3.8
        uses: actions/setup-python@v4
        with:
            python-version: '3.9' # this will set up python 3,.9 as default 
            cache: 'pip' # caching pip dependencies: 
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          python --version 
      - name: build docker iamge
        run: echo "build docker image" 
